spring.application.name=EmployeeManagement

# Database Configuration
spring.datasource.url=jdbc:postgresql://db.dcujfppnieimvvejzjrs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=JAM_ERP#5@26

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=adi
spring.security.user.password=1234


# Optional
spring.jpa.properties.hibernate.format_sql=true
